///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoronaStatusCountryInfo {
/*
{
  "_id": 50,
  "iso2": "BD",
  "iso3": "BGD",
  "lat": 24,
  "long": 90,
  "flag": "https://disease.sh/assets/img/flags/bd.png"
} 
*/

  int? Id;
  String? iso2;
  String? iso3;
  int? lat;
  int? long;
  String? flag;

  CoronaStatusCountryInfo({
    this.Id,
    this.iso2,
    this.iso3,
    this.lat,
    this.long,
    this.flag,
  });
  CoronaStatusCountryInfo.fromJson(Map<String, dynamic> json) {
    Id = json["_id"]?.toInt();
    iso2 = json["iso2"]?.toString();
    iso3 = json["iso3"]?.toString();
    lat = json["lat"]?.toInt();
    long = json["long"]?.toInt();
    flag = json["flag"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["_id"] = Id;
    data["iso2"] = iso2;
    data["iso3"] = iso3;
    data["lat"] = lat;
    data["long"] = long;
    data["flag"] = flag;
    return data;
  }
}

class CoronaStatus {
/*
{
  "updated": 1628876618495,
  "country": "Bangladesh",
  "countryInfo": {
    "_id": 50,
    "iso2": "BD",
    "iso3": "BGD",
    "lat": 24,
    "long": 90,
    "flag": "https://disease.sh/assets/img/flags/bd.png"
  },
  "cases": 1405333,
  "todayCases": 8465,
  "deaths": 23810,
  "todayDeaths": 197,
  "recovered": 1273522,
  "todayRecovered": 11457,
  "active": 108001,
  "critical": 1389,
  "casesPerOneMillion": 8440,
  "deathsPerOneMillion": 143,
  "tests": 8342190,
  "testsPerOneMillion": 50099,
  "population": 166513298,
  "continent": "Asia",
  "oneCasePerPeople": 118,
  "oneDeathPerPeople": 6993,
  "oneTestPerPeople": 20,
  "activePerOneMillion": 648.6,
  "recoveredPerOneMillion": 7648.17,
  "criticalPerOneMillion": 8.34
} 
*/

  int? updated;
  String? country;
  CoronaStatusCountryInfo? countryInfo;
  int? cases;
  int? todayCases;
  int? deaths;
  int? todayDeaths;
  int? recovered;
  int? todayRecovered;
  int? active;
  int? critical;
  int? casesPerOneMillion;
  int? deathsPerOneMillion;
  int? tests;
  int? testsPerOneMillion;
  int? population;
  String? continent;
  int? oneCasePerPeople;
  int? oneDeathPerPeople;
  int? oneTestPerPeople;
  double? activePerOneMillion;
  double? recoveredPerOneMillion;
  double? criticalPerOneMillion;

  CoronaStatus({
    this.updated,
    this.country,
    this.countryInfo,
    this.cases,
    this.todayCases,
    this.deaths,
    this.todayDeaths,
    this.recovered,
    this.todayRecovered,
    this.active,
    this.critical,
    this.casesPerOneMillion,
    this.deathsPerOneMillion,
    this.tests,
    this.testsPerOneMillion,
    this.population,
    this.continent,
    this.oneCasePerPeople,
    this.oneDeathPerPeople,
    this.oneTestPerPeople,
    this.activePerOneMillion,
    this.recoveredPerOneMillion,
    this.criticalPerOneMillion,
  });
  CoronaStatus.fromJson(Map<String, dynamic> json) {
    updated = json["updated"]?.toInt();
    country = json["country"]?.toString();
    countryInfo = (json["countryInfo"] != null)
        ? CoronaStatusCountryInfo.fromJson(json["countryInfo"])
        : null;
    cases = json["cases"]?.toInt();
    todayCases = json["todayCases"]?.toInt();
    deaths = json["deaths"]?.toInt();
    todayDeaths = json["todayDeaths"]?.toInt();
    recovered = json["recovered"]?.toInt();
    todayRecovered = json["todayRecovered"]?.toInt();
    active = json["active"]?.toInt();
    critical = json["critical"]?.toInt();
    casesPerOneMillion = json["casesPerOneMillion"]?.toInt();
    deathsPerOneMillion = json["deathsPerOneMillion"]?.toInt();
    tests = json["tests"]?.toInt();
    testsPerOneMillion = json["testsPerOneMillion"]?.toInt();
    population = json["population"]?.toInt();
    continent = json["continent"]?.toString();
    oneCasePerPeople = json["oneCasePerPeople"]?.toInt();
    oneDeathPerPeople = json["oneDeathPerPeople"]?.toInt();
    oneTestPerPeople = json["oneTestPerPeople"]?.toInt();
    activePerOneMillion = json["activePerOneMillion"]?.toDouble();
    recoveredPerOneMillion = json["recoveredPerOneMillion"]?.toDouble();
    criticalPerOneMillion = json["criticalPerOneMillion"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["updated"] = updated;
    data["country"] = country;
    if (countryInfo != null) {
      data["countryInfo"] = countryInfo!.toJson();
    }
    data["cases"] = cases;
    data["todayCases"] = todayCases;
    data["deaths"] = deaths;
    data["todayDeaths"] = todayDeaths;
    data["recovered"] = recovered;
    data["todayRecovered"] = todayRecovered;
    data["active"] = active;
    data["critical"] = critical;
    data["casesPerOneMillion"] = casesPerOneMillion;
    data["deathsPerOneMillion"] = deathsPerOneMillion;
    data["tests"] = tests;
    data["testsPerOneMillion"] = testsPerOneMillion;
    data["population"] = population;
    data["continent"] = continent;
    data["oneCasePerPeople"] = oneCasePerPeople;
    data["oneDeathPerPeople"] = oneDeathPerPeople;
    data["oneTestPerPeople"] = oneTestPerPeople;
    data["activePerOneMillion"] = activePerOneMillion;
    data["recoveredPerOneMillion"] = recoveredPerOneMillion;
    data["criticalPerOneMillion"] = criticalPerOneMillion;
    return data;
  }
}
