///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoronaTimestampsBangladesh {
/*
{
  "date": "2020-1-22",
  "confirmed": 0,
  "deaths": 0,
  "recovered": 0
} 
*/

  String? date;
  int? confirmed;
  int? deaths;
  int? recovered;

  CoronaTimestampsBangladesh({
    this.date,
    this.confirmed,
    this.deaths,
    this.recovered,
  });
  CoronaTimestampsBangladesh.fromJson(Map<String, dynamic> json) {
    date = json["date"]?.toString();
    confirmed = json["confirmed"]?.toInt();
    deaths = json["deaths"]?.toInt();
    recovered = json["recovered"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["date"] = date;
    data["confirmed"] = confirmed;
    data["deaths"] = deaths;
    data["recovered"] = recovered;
    return data;
  }
}

class CoronaTimestamps {
/*
{
  "Bangladesh": [
    {
      "date": "2020-1-22",
      "confirmed": 0,
      "deaths": 0,
      "recovered": 0
    }
  ]
} 
*/

  List<CoronaTimestampsBangladesh?>? bangladesh;

  CoronaTimestamps({
    this.bangladesh,
  });
  CoronaTimestamps.fromJson(Map<String, dynamic> json) {
    if (json["Bangladesh"] != null) {
      final v = json["Bangladesh"];
      final arr0 = <CoronaTimestampsBangladesh>[];
      v.forEach((v) {
        arr0.add(CoronaTimestampsBangladesh.fromJson(v));
      });
      bangladesh = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (bangladesh != null) {
      final v = bangladesh;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["Bangladesh"] = arr0;
    }
    return data;
  }
}
